twitter:
  query:
    terms: nike, tesla, nasa
    languages: en

spring:
  cloud:
    stream:
      bindings:
        output:
          content-type: application/json
          destination: tracking
          producer:
            partitionCount: 1
            headerMode: raw
      kafka:
        binder:
          brokers: localhost:9092